name: Playwright CI

on:
  workflow_dispatch:

  schedule:
    - cron: '30 4 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Project
        run: mvn clean compile

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"
        # --- ADD THIS STEP HERE ---
      - name: Create credentials.json
        run: |
          mkdir -p src/main/resources
          echo '${{ secrets.GCP_CREDENTIALS }}' > src/main/resources/credentials.json
      # ---------------------------
  # --- ADD THIS STEP TO FIX THE NEW ERROR ---
      - name: Install Playwright Dependencies
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Run Maven Tests
        run: mvn test
      - name: Run Tests
        run: mvn test
