name: Playwright CI

on:
  workflow_dispatch:

  schedule:
    - cron: '30 4 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Project
        run: mvn clean compile

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"
        # --- ADD THIS STEP HERE ---
      - name: Create credentials.json
        run: |
          mkdir -p src/main/resources
          echo '${{ secrets.GCP_CREDENTIALS }}' > src/main/resources/credentials.json
            # CHANGE 1: Install the actual browser and system libraries
      - name: Install Playwright Browsers & Deps
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      # CHANGE 2: Wrap the test command with xvfb-run
      - name: Run Maven Tests
        run: xvfb-run mvn test
